name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.3'

      - name: Go build
        run: go build ./cmd/olcrtc-manager

      - name: Go test
        run: go test ./cmd/olcrtc-manager/ -v